### ISSUE TITLE
Request for Donation link (KoFi/Paypal/Similar)

### ISSUE THREAD

**Issue by Xasin** [2walker2/Astral-Codex#16]
Hi!

I just finished playing through the mod, and frankly it was a fascinating and great experience!

It added to the base game, and much like the base game's DLC it managed to expand the world and story, fleshing out new areas (in this case the source of the Interloper, tacking on a unique chain of events that has this neat, central tie)

There were no hiccups except maybe needing a moment to get the Population adjustment, which was fine.

One other note is that it might be nice to give a bit more detail on the people we are interacting with. The mod never quite clarified whether or not some of them were *actively* interacting with the Hearthian's own Universe, or if it all was simply automated recordings and the Translation system creating a readable interface, but that's a very minor note.

As such, I would love to donate and give back to you, as I did enjoy the experience, and I'd love to support such creativity :)
If you have any links or projects you'd want to see supported, do please tell :D

**Comment by 2walker2** [comment]
Hello,
Sorry it took me a while to respond to this. There isn't a donation link for the project because I'm not the only one who worked on it. There isn't really a fair way of distributing donations between all contributors as each contributed to a different extent. I do appreciate your desire to donate though, so I'd like to request that any donation you would have directed at this project instead be contributed to the prize pool for the next community modding jam. Astral Codec wouldn't exist without the rest of the Outer Wilds modding community and I would love to see future jams supported.
Thank you,
Walker

PS. To answer your question, the precursors (they don't really have a name, even internally) never directly interact with the Hearthians' universe. All the text you read in-game is either pre-recorded or automatically generated by the Chime's computer. Most pre-recorded messages are prefaced by something like "retrieving pre-recorded message" or are enclosed in quotes (the exception being at the Eye).
